### ISSUE TITLE
Replace `thenify` with `util.promisify`

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#389]
Not only does this allow us to get rid of an extra package and use the node's builtin utility, it also allows us to get rid of crappy `any-promise` module because from what I can see, `thenify` is the only one who uses it as a dependency.

In return, this should allow us to get rid of this webpack plugin: https://github.com/ShieldBattery/ShieldBattery/blob/master/common.webpack.config.js#L107

**Comment by tec27** [comment]
You should make sure this is supported by webpack before you try to do this. Last time I tried, webpack's version of util didn't have this method, so it wasn't really possible. (util.promisify also has somewhat different features/API, but that's probably not terrible to work around)

**Comment by 2Pacalypse-** [comment]
Will do.

Although, annoyingly, I just noticed that `any-promise` is a dependency on the server of some koa-related deps, so I'm not sure if we'll be able to get rid of it completely. I think it's still worth it to replace `thenify` with `util.promisify` just because it's a built-in feature of Node. What do you think?

**Comment by tec27** [comment]
I would guess that things like thenify will be less-maintained now that the functionality is (mostly) built into node itself, so yeah, it seems worthwhile. any-promise is just a promise polyfill, it's only problematic on the webpack side of things because it does weird stuff (IIRC), having it as a dep of server things still isn't really a big deal.

**Comment by 2Pacalypse-** [comment]
Guess we have to wait on https://github.com/defunctzombie/node-util/issues/20 before we can do this.
