### ISSUE TITLE
Errors from map uploading aren't being handled

### ISSUE THREAD

**Issue by neivv** [ShieldBattery/ShieldBattery#450]
Trying to upload a broken map, for example `echo asdasd > invalid.scx` causes both a server-side error and breaks the clientside map browse until refresh.

The clientside breakage is probably more or less expected considering it intentionally doesn't render anything if an error has occured https://github.com/ShieldBattery/ShieldBattery/blob/master/client/maps/browse-local-maps.jsx#L43 Doesn't make it user-friendly though.

(FWIW I didn't actually upload an intentionally broken map when running into this but got a timeout due to pc being overloaded)

**Comment by 2Pacalypse-** [comment]
Hmm, they should be.
Just a few lines from the one you linked is this code: https://github.com/ShieldBattery/ShieldBattery/blob/master/client/maps/browse-local-maps.jsx#L34-L39

So when an error during upload happens, overlay should close and a snackbar should show an error message (I know it's still pretty crude way to deal with it, but this shouldn't happen that often that I think is fine for now). That's why that line you linked returns `null` when an error happens; because the overlay should close anyway (probably should change this to not close the overlay though and just show the snackbar).

Oh and yeah, I completely forgot we have a 60s timer on map parsing ^^. I was planning on reworking the parser code anyway in future (by implementing some kind of a queue pattern), so we could revisit that timer then.

(I'll test this a bit more to try to figure out what happened exactly in your case)

**Comment by neivv** [comment]
Oh, I mean that the issue is that afterwards `lastError` stays set in redux state, and trying to reopen local map browse then will just give a black screen.

**Comment by 2Pacalypse-** [comment]
Oh, so you're right.
I clear the server map browser redux state when it exits, but forgot to do the same for the local browser ^^. Will fix.

**Comment by 2Pacalypse-** [comment]
This should be fixed now.

There was no need to clear the redux state; just remove that line you linked initially where nothing was rendered if error happened while uploading. I have no idea why I added that in the first place ^^.

I also stopped closing the overlay when an error during upload happens, as I think that could get pretty annoying if it's just a temporary error.
