### ISSUE TITLE
Slider component feels laggy when dragged

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#478]
Not sure if it was like this prior to the styled-components change, but it needs to be profiled/fixed.

**Comment by 2Pacalypse-** [comment]
I took a look into this a bit, and from what I can tell, there are two different issues here:
- slider is laggy when _dragged_
- slider is laggy when _holding_ down the left/right key

Both of those seem to be caused by transition duration, which is longer than it takes for the values to get continuously updated while dragging/holding down a key, which in effect makes them appear laggy. After some trial and error, this is what "fixed" these issues for me:
- turn off transition duration completely when dragging with mouse
- setting transition duration to 30ms at most when holding down the left/right key

Do you think that's an ok way to "fix" this issue?

EXTRA INFO: There is a very weird "bug" that's happening when holding down the left/right key. It's most visible when there are a lot of steps in a slider, say a 100. Holding down the key transitions the filled track pretty fluidly (which uses `scaleX` to transition), but transitioning the balloon is pretty much blocked completely until the track finishes its transition (which uses `translateX` to move the balloon). However, changing `scaleX` and `translateX` transitions to `width` and `left` transitions respectively, fixes this issue. Which is pretty unintuitive since I thought `transform` is better to use as a transition property. I have no idea what's going on here. But in any case, this is "fixed" by lowering the transition duration while dragging/holding down a key anyway.

**Comment by tec27** [comment]
That sounds like a reasonable fix, yeah.

As for the extra stuff, using `width` and `left` is maybe not ideal since it would be triggering layouts, but I guess if we set the proper `contain`s on the component maybe that's very cheap to do?
