### ISSUE TITLE
Matchmaking map pools should use IDs instead of map hashes

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#506]
If we're registering game results by map ID, then we need to know the map ID when a game starts through matchmaking. Currently, there isn't really an easy way to do that, as we'd have to go from a map hash -> a particular instance of that map having been uploaded. I could write a query to just pick the first instance, but it's probably better to actually pick the "official" map as intended by the admin that set the map pool.

**Comment by 2Pacalypse-** [comment]
Hmm, can you clarify this a bit more please? I was certain I made sure that we're using map IDs everywhere instead of map hashes, but maybe I missed something?

The only thing that I can see that might be causing confusion is that I named the variables [here](https://github.com/ShieldBattery/ShieldBattery/blob/master/server/lib/wsapi/matchmaking.js#L196-L206) `preferredMapsHashes` and `randomMapsHashes`, when in fact those are map IDs, not hashes. I have no idea why I named those variables as "hashes", instead of IDs.

**Comment by tec27** [comment]
Yeah you are correct. I didn't have any data in my local DB for these to easily inspect the type so I looked through the various migrations, but I guess I didn't quite find the latest ones because these still looked like `bytea`s to me. I'll rename the variables as I update this stuff
