### ISSUE TITLE
Allow users to upload a profile image.

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#518]
A few things that I'm unsure about:
- Do we restrict which file types users can upload (.jpg and .png?)
- What should be the file size limit (a few MBs?)
- Should we do _anything_ with the image that the user uploads (like trying to optimize it, lower its size, etc.)

**Comment by tec27** [comment]
We're probably gonna wanna process any image that gets uploaded so that it:
- Doesn't include private info (EXIF data, etc.)
- Is sized correctly
- Is optimized for transfer and has reasonable quality settings

Definitely should have some kind of size limit for uploads to limit what we have to process, although I don't have an exact number in mind. Should probably try to figure out what the right approach to the above things is and decide if it's worth it right now. A different approach would be that we provide avatars to select from (and maybe allow them to unlock more somehow?). It requires more work to generate the content but limits the amount of work we have to do for processing + moderating user choices. For the moment maybe a stand-in for that content could just be picking a color or something.

**Comment by 2Pacalypse-** [comment]
Yeah, allowing users to pick their avatar color or have some kind of a repository of avatars to choose from seem like decent alternatives, but if we're gonna allow users to upload their own images eventually, we might as well do it now :d. I also think users might appreciate it a bit more than the alternatives, since they're probably used to it from using Discord and such.

I haven't personally done much in image manipulation department, so I might need some help in doing some of those things, but I assume there are libraries that can help there too?

As far as the moderation goes, I was thinking of adding an option in user profiles for admins to delete their profile image, and eventually ban them if they're repeat offenders. Not sure how Discord deals with inappropriate avatars.

**Comment by tec27** [comment]
Well, my alternative approach would be a permanent thing, I think (no uploads). I don't have much of a preference either way though, games seem to have a mix of approaches here. (Well, namely things on Steam usually use the Steam avatar, and things off steam have preset avatars to select from/unlock :) )

As far as processing images goes, there are definitely libraries out there to do it. ImageMagick is probably a common approach, although leaves things to be desired as far as security (this post mentions some considerations: https://lcamtuf.blogspot.com/2016/05/clearing-up-some-misconceptions-around.html )

Moderation options sound good to me (can't remember if we ever added some general audit log of all mod actions on a user, but we probably want something like that as we add more of this stuff)

**Comment by 2Pacalypse-** [comment]
I guess games don't really allow users uploading custom avatars usually (besides Steam), but I always compared us more to Discord than to other game clients :d. I assume other games don't really want to deal with moderation of it all, which is why community aspects of the game clients seem more like an afterthought.

I'll definitely need to do some reading on image manipulation libraries, but I feel like it's not _that_ much work if we "only" need to remove EXIF data, limit the size, and configure quality settings ^^. I could definitely use some concrete numbers on those things if you have them; or at least some guidelines on which to choose them.

I guess it might be worth putting this feature behind a feature flag too? So we could configure those numbers until we get them right, before making it available.

**Comment by tec27** [comment]
I think the added benefit of only allowing presets is that the avatars can be a form of progression. For instance, Diabotical gates most of their avatar choices behind achievements and battle pass unlocks. They also have a system where streamers can register an avatar with them, and whenever people watch that person's stream, they have a chance of unlocking that avatar for usage. It's not the *only* sort of progression you could do like that, but it is something.

I don't think the image stuff will be that hard, it's just a matter of picking the right library/approach. I don't have hard numbers because it's something you need to determine from the sizes of images you expect, how much it takes to process them, etc. You can probably look around at all the various sites that allow avatar uploads and see what their ranges are to get a reasonable idea.

Feature flags are mainly useful if the work takes more than a commit to complete. If you want to be able to check in parts of this work and not have to keep a branch maintained over a long period, that's what feature flags are for. If you anticipate that the work won't be ready to use after you've built the user-facing features (e.g. because it needs more moderation tools or whatever), then yes, a feature flag probably makes sense.

**Comment by 2Pacalypse-** [comment]
Yeah, using avatars as a form of progression is a nice idea. But we can achieve that with some kind of profile portraits or whatever games use these days too. And we can even do what Discord does and make the animated profile images available to long term users or something.

As far as the right library goes, I think sharp (https://github.com/lovell/sharp) looks pretty promising. I'll try to play around with actual numbers and see how stuff feels. And yeah, I don't think a feature flag is necessary since everything should be done in a single PR.

**Comment by tec27** [comment]
Yeah, that does look pretty good. May be useful for the map processing stuff too if we could avoid doing that byte shuffling we do currently to go from 3 -> 4 bytes per pixel (or vice versa? can't recall)

**Comment by 2Pacalypse-** [comment]
After a bit more thinking and discussion on this feature, I've changed my mind on this feature, and now think that it might be a better option (and easier one to implement/maintain) to have a pool of avatars uploaded by us that users can choose from (including the progression -> unlocking special avatars system).
