### ISSUE TITLE
Map picker picks the wrong map folder when SC:R client is active

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#523]
Steps to reproduce:
1) Hit the "create" button
2) Hit "Browse maps"
3) Go to "My maps"
4) Hit the upload button at the bottom

Expected: `<CurrentUser>/Documents/Starcraft/maps` folder would be open
Actual: `<StarCraft Path>/Maps/` is open

Relatedly, maybe we should provide a direct file upload for this as well? (That a file can be dragged into, or opens a file picker)

**Comment by neivv** [comment]
SC:R actually reads both of those directories in its ingame map picker and shows the files from both (Not sure what happens if there are equivalent filenames). Should that be replicated?

For me the Documents/ path is pretty empty compared to install directory that has all the maps from pre-remastered patches.

**Comment by 2Pacalypse-** [comment]
From what I can deduce looking at those two folders on my computer.
- `<StarCraft Path>/Maps/` is the folder containing the maps that are installed with StarCraft
- `<CurrentUser>/Documents/StarCraft/maps` is the folder containing the maps downloaded on battle.net

I can't remember my initial thinking when I chose the former as the default folder, but looking at it from the perspective of a new player who just installed the game to play on ShieldBattery; their downloads folder would be empty, so I assumed we want to give them _some_ maps as an option. Especially since we don't use the SC:R's downloads folder to store user's maps, that folder will remain empty until they download some maps on the battle.net or manually put some maps in there.

I definitely did plan on implementing some sort of a direct file upload mechanism to address this issue though, and also to potentially allow users to upload multiple maps at once.

If you feel like we'll get more value out of using the downloads folder, it's a simple change. Probably the "ideal" solution would be to use both folders as SC:R does, but I'm not sure if it's worth investing time into that.

**Comment by tec27** [comment]
I wouldn't mind being able to navigate both, but currently there's no way to get above the root maps folder. I personally have some ICCup map packs in the newer folder but not in the SC directory, so it's been sort of annoying for me when testing things.

I don't know if we need to support both as in show them in combination, maybe just a button or a dropdown or something to change between them would be fine?

**Comment by 2Pacalypse-** [comment]
If we're gonna add a button, might as well just make that button a file picker? :d
Unless we don't want to have a file picker (since it's kind of weird as our file browser already _is_ a file picker in a way ^^), and instead just have the map browser serve as some kind of a dropzone for dragged map files.

**Comment by tec27** [comment]
I mean I guess, mainly the reason I see a dropdown-type-thing being useful is because we know of 2 potentially useful folders, the filepicker would require the user to find the thing they want (and a lot of people don't necessarily know where these folders are off-hand). 

I do think this whole map browser probably becomes less useful as our system gets more use, as it's more likely that the maps people want would have already been uploaded anyway (once we allow publication by non-staff anyway :) ). So probably in that case we should be optimizing more for the people *making* maps or something, but I dunno. I think picking the Documents folder and adding a visible drop-zone for files (that can open a file browser if clicked?) seems like a reasonable compromise for the moment. It is at least easily explainable.

**Comment by 2Pacalypse-** [comment]
Hmm, I think the easiest thing to do might be to just do what SC:R does, and just read both folders and join them; by putting the contents of `<CurrentUser>/Documents/Starcraft/maps` folder in the `<StarCraft Path>/Maps/downloads` folder (overriding it if it already exists there?). What do you think?

**Comment by tec27** [comment]
I guess that depends on what you mean by "easiest" :) I still think the simplest thing is adding a button somewhere to swap between the folders, but you if you want to spend the time to write an actual solution, have at it.

**Comment by 2Pacalypse-** [comment]
This was done in https://github.com/ShieldBattery/ShieldBattery/commit/c2dfc958e9a268b9ffc3a932aeeb4c1e99e6a1b6

The approach taken was the one where we allow choosing between the StarCraft's default folder and the downloads folder. An issue has been filed for a better approach which would make that mostly unnecessary here: https://github.com/ShieldBattery/ShieldBattery/issues/600
