### ISSUE TITLE
Underline letter on hotkey buttons

### ISSUE THREAD

**Issue by GrantJenk** [ShieldBattery/ShieldBattery#532]
One thing I always thought was cool about the menus in Brood War was that they highlighted or underlined which letter can be pressed to activate the button. I thought it might be nice to mimic that. 

Possibly only add the underline or whatever other visual display when the alt key is pressed?

**Comment by 2Pacalypse-** [comment]
As someone who tries to use the keyboard as much as possible when using ShieldBattery, I'm a big fan of this idea.

But yeah, adding an underline only when the alt key is pressed makes more sense to me, because otherwise it might not be immediately obvious to users what is the modifier key that needs to be pressed with the underlined one.

**Comment by 2Pacalypse-** [comment]
After seeing that people have problems with discoverability of these hotkeys (including some of our main developers! :p), maybe always showing an underline on hotkey buttons isn't the craziest of ideas. Still unsure how it'll look visually and if it'll impact the design too much, but only way to find that out is to try it ^^.
