### ISSUE TITLE
Matchmaking for Random Race improvements

### ISSUE THREAD

**Issue by coin-au-carre** [ShieldBattery/ShieldBattery#630]
So I was trying the beta and launched  3 games as 'R' race with  Use alternate race 'T' to avoid mirror matchups. 

I was a little disappointed to have encountered 3 TvT so I digged a little in the code and I understood that was not that simple

The current code is straightforward in `server\lib\wsapi\matchmaking.ts`:

```ts
if (playersHaveSameRace && players.every(p => p.useAlternateRace === true)) {
  // All players have the same race and want to use an alternate race; select randomly one
  // player to use the alternate race and everyone else their main race. This is only done for
  // the first player, as the whole concept of the alternate race doesn't make much sense when
  // there are more than two players.
  const randomPlayerIndex = getRandomInt(players.size)
  slots = players.map((p, i) =>
    createHuman(p.name, p.id, i === randomPlayerIndex ? p.alternateRace : p.race),
  )
} else if (playersHaveSameRace && players.some(p => p.useAlternateRace === true)) {
  // All players have the same race, but only some of them are choosing to use an alternate
  // race; find the first player who wants to use the alternate race and have everyone else
  // use their main. Again, this is only done for the first player.
  const useAlternateRacePlayer = players.find(p => p.useAlternateRace === true)!
  slots = players.map(p =>
    createHuman(p.name, p.id, p.id === useAlternateRacePlayer.id ? p.alternateRace : p.race),
  )
} else {
  // All players have different race or don't want to use alternate race; nothing special to
  // do here.
  slots = players.map(p => createHuman(p.name, p.id, p.race))
}
```

In my case, there are 3 possibilities (one for each condition) which explain why I had several TvTs: 

1. My opponent has picked 'R' and has chosen an alternate race. We are in the `if (playersHaveSameRace && players.every(p => p.useAlternateRace === true))` case. One of us was chosen to use the alternate race by SB (me or the opponent if he has picked 'T' as an alternate race) and unfortunately the other one was chosen randomly as T by BW.
2. My opponent has picked 'R' but has no alternate race. We are in the `else if (playersHaveSameRace && players.some(p => p.useAlternateRace === true))` case. I was then chosen to play as 'T' by SB and my opponent was chosen randomly as T by BW. 
3. My opponent has picked 'T' so we were in the `else` case since 'R' and 'T' are considered different race, So BW launched as 'TvR'. I was unlucky and T was chosen randomly for me by BW (and not SB)

Note that in the 1st and 2nd cases, **one of the player is at disadvantage since one can be seen as 'R' in the game whereas the other has his/her race picked by SB.  I will call this advantage to be seen as 'Random' in BW game: the 'In game Random advantage'.**

Therefore, I have several propositions to improve the Matchmaking for random people (who hate mirror MUs also) and be "fair" as much as possible:

- If the two players are random and have chosen different alternate races to avoid mirrors, we should favor non mirror matchup. Hence SB should handle the randomness and we should show MU races over 'In game Random Advantage'. 
- If the two players are random and have chosen the same alternate races then both of them should be launched as 'R' by SB and both can have the 'In game Random advantage' (we should not favor one player over another).
- If the two players are random and only one has chosen a different alternate race then both of them should be launched as 'R' by SB. this one can be discussed but I think the one who assume every MUs possible should be favored more  than the other. 
- If the two players are random and have no alternate races so both of them should be launched as 'R' by SB. We should fall in the `else`  condition **which is not currently the case** since 2 Randoms are considered the same race according to SB.
- If one player has picked a specific race and the other one has picked 'R' with the option an alternate race.  then SB should handle the randomness to avoid mirror MUs for the 'R' player. We can still display 'R' in SB but in BW the race will be picked. 

For later, a nice to have option for random people who would favor  'In game Random advantage' would be the ability to choose:

  - 1st option: "I prefer avoiding mirror MUs over  In Game Random advantage". SB will handle the randomness, we can still display Random in SB but in BW the race will be picked. IMO this should be the default behavior. 
  - 2nd option: "I prefer to have the In Game Random advantage" over mirror MUs. 

I think both options could be nice to have if we explain well for random players the pros and cons for the 2 options. Personally  as a random player, I do not like mirror MUs! so I think we should implement the propositions mentioned above and see this nice to have later.

If that's ok for you I would be glad to be assigned and work on that, since I would like to participate in the 2v2 and 3v3 matchmakings that would be a good training.

**Comment by tec27** [comment]
I think we should just disable alternate race picking for Random. With non-random races, if you pick an alternate race, you have the same number of matchups to worry about (3). With Random (if implemented how people *think* it works), if you pick an alternate race, you are actually *removing* 3 matchups from the game that you never have to worry about. This wasn't really the intention, it's just a bug in the implementation (or an oversight in the initial feature design). I noticed this prior to launch but left it in because it didn't seem harmful in it's current implementation, but obviously people are confused about the effects.

We definitely don't want to be in the business of reimplementing BW's random race selection logic, as it's actually quite complex,  so I don't want to get into selecting random races outside the game itself. It also already avoids mirror matchups if both players are random (there's a 1/24 chance of a mirror in a game with 2 players that are both random).

The main idea of the alternate race thing is that it simplifies what is otherwise a quite complex UI for allowing racepicking by serving the main case that people usually racepick for (mirrors), so I'm not a fan of adding any further complexity to that selection.

So the work is probably:
1) Update the find match form such that if random is selected, the alternate race checkbox is disabled and unchecked
2) Update the matchmaking preferences API to disallow alternate race selection with random
3) Update the matchmaking race resolution logic such that `playersHaveSameRace` is only true if the players are *not* random

This will leave players that have previously selected an alternate race with random in the same state in the DB, but once they enter matchmaking again it should update (and 3 protects against it having an effect anyway)

**Comment by coin-au-carre** [comment]
I understand, your solution is also fine for me since it is coherent and it will be much simpler indeed.
I still find interesting to be able to have our own random race selection logic but we could always ask the community if they think it should be a cool thing to do. 
 > (there's a 1/24 chance of a mirror in a game with 2 players that are both random).
Not sure I have understood correctly but theoretically you should have 1/3 chance to get mirror match up with 2 random players. Is there a hidden biaised random selection by Blizzard I am not aware of ?  (I know that in 2v2 if everybody are random, you have one of each race at least). 

To be sure to understand your tasks

> 1. Update the find match form such that if random is selected, the alternate race checkbox is disabled and unchecked

OK on the front end side I presume

> 2. Update the matchmaking preferences API to disallow alternate race selection with random

I m not sure about the difference with 1. this change concerns the back end side only to ensure you are not in a incoherent state ?

> 3. Update the matchmaking race resolution logic such that playersHaveSameRace is only true if the players are not random

Yes, I think that's it!


If it's fine with you I am willing to be assigned to this.

**Comment by tec27** [comment]
> I understand, your solution is also fine for me since it is coherent and it will be much simpler indeed.
> I still find interesting to be able to have our own random race selection logic but we could always ask the community if they think it should be a cool thing to do later on.
> 
> > (there's a 1/24 chance of a mirror in a game with 2 players that are both random).
> 
> Not sure I have understood correctly but theoretically you should have 1/3 chance to get mirror match up with 2 random players. Is there a hidden biaised random selection by Blizzard I am not aware of ? (I know for instance that in 2v2 if everybody is random, you have one of each race at least).

https://tl.net/forum/brood-war/413197-few-mirrors-when-both-players-random#18

After reading that you might understand why I don't want to reimplement it :)

> 
> To be sure to understand your tasks
> 
> > 1. Update the find match form such that if random is selected, the alternate race checkbox is disabled and unchecked
> 
> OK on the front end side I presume

Yes, in the React code, correct.

> 
> > 1. Update the matchmaking preferences API to disallow alternate race selection with random
> 
> I m not sure about the difference with 1. this change concerns the back end side only to throw an error if the app asks for it ?

Correct. We generally need to make sure that our API is resilient to people sending requests with things even if we disallow it through the UI, because people can e.g. make these requests with other tools, modify their client, etc. and we don't want to open ourselves up to people bypassing our restrictions by doing so.
 
> > 1. Update the matchmaking race resolution logic such that playersHaveSameRace is only true if the players are not random
> 
> Yes, I think that's it!
> 
> If it's fine with you, I work on that and willing to be assigned to this issue.

Yep! Feel free!

**Comment by coin-au-carre** [comment]
> https://tl.net/forum/brood-war/413197-few-mirrors-when-both-players-random#18

Wow really interesting thanks :)

Ok understood for the 2. !
