### ISSUE TITLE
User overlay can render below screen

### ISSUE THREAD

**Issue by GrantJenk** [ShieldBattery/ShieldBattery#641]
When clicking on a user in the userlist that's near the bottom of the screen, part of the overlay will render below the screen.

**Comment by tec27** [comment]
Good catch, the menus in the map browser actually do this as well.  The problem is basically that our "safe zone" logic only operates if the anchor is on the corner that is nearest the window edge. I think that function has all the info it needs already, but doesn't attempt to make those checks right now.
