### ISSUE TITLE
Chat channel creation input accepts '&' when the server does not

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#648]
Might be some other invalid characters it accepts too, unsure.

The failure case here isn't great either: it shows a loading  screen forever with the title set to the URI encoded value

**Comment by adaugherty42** [comment]
The issue is that the server is getting the hex values for these characters (e.g. %24 for $), and the "%" is tripping up against the channel name regex. It's easy enough to throw a `decodeURIComponent` in the channel name validator function (and also in the client component), but I noticed a commit a few days ago for a similar issue with lobby names. I'm totally unfamiliar with the codebase...is a broader fix possible here?

**Comment by tec27** [comment]
The server shouldn't need to decode anything because it's in the body, not the URL. It looks like the ChatChannelView isn't properly decoding its props, I'll just fix it
