### ISSUE TITLE
Some popovers do not stay anchored on resizing window

### ISSUE THREAD

**Issue by GrantJenk** [ShieldBattery/ShieldBattery#691]
When resizing the window with a popover open, the popover won't follow the anchor element.
Looks like the `SelfProfileOverlay` actually does follow the anchor

![popover-not-anchored](https://user-images.githubusercontent.com/43507279/120138777-cc34bf80-c19c-11eb-90c8-c2ab69535c32.png)

**Comment by tec27** [comment]
Think SelfProfileOverlay works only because it's on the left side (and thus is always relative to 0, not changed by resizing). Probably need some way to wire a ResizeObserver from the popover's `PositioningArea` into `useAnchorPosition`.

Problem looks to me to be that the popover itself gets rerendered on resize, but it doesn't cause its parent to be re-rendered, and thus `useAnchorPosition`'s result is out of date

**Comment by tec27** [comment]
Or I guess maybe we could just hook up a window resize handler, since popovers area is just the whole window?
